brew 'bash'
brew 'bash-completion'
brew 'zsh'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'the_silver_searcher'
brew 'git'
brew 'python'
brew 'python3'
brew 'ruby'
brew 'node'
brew 'vim', args: ['with-lua', 'with-luajit']
brew 'ctags'
brew 'mysql'
brew 'autossh'
brew 'mas'

tap 'beeftornado/rmtree'
brew 'beeftornado/rmtree/brew-rmtree'

cask 'macvim'
